# yaml-language-server: $schema=https://raw.githubusercontent.com/xylex-group/xbp/main/schemas/xbp.project.schema.json
project_name: dexter-chrome
version: 0.1.0
port: 8080
build_dir: ./
app_type: chrome-extension-manifest-3
build_command: null
start_command: null
install_command: null
environment: null
services: null
openapi: null
workers: null
systemd_service_name: null
systemd: null
kafka_brokers: null
kafka_topic: null
kafka_public_url: null
log_files: null
monitor_url: null
monitor_method: null
monitor_expected_code: null
monitor_interval: null
database: null
target: chrome-extension-manifest-3
branch: main
crate_name: null
npm_script: null
port_storybook: null
url: null
url_storybook: null
linear: null
github: null
publish: null
version_targets: []
version_domains: []
ignore_paths: []
watch_ignore_paths: []
versioning_disabled: []
release_disabled: []
